### ISSUE TITLE
[feature request] Option to keep the dock on primary screen

### ISSUE THREAD

**Issue by kugelblitz** [window-maker/wmaker#24]
Hello,

Thank you for supporting WindowMaker.

I have the dock attached to the right border of the screen. I also have a second monitor which is configured via XRandR to be on the right side of my primary monitor. This causes the dock to move to the second monitor and attach to its right border because it seeks to be on the right border of the "whole" merged screen. This is not always wanted, not in my case.

It would be great to have the option to keep the Dock on primary screen.

**Comment by tstraus13** [comment]
Just figured I'd chime in here too. I am liking WindowMaker but I have a three monitor setup going left to right, all horizontal. The dock either wants to be on the left side of the left monitor or the right side of the right monitor. I can not get it positioned on the center monitor. It would be great if it were more "aware" of the connected monitors. I believe it has something to do with Xinerama and X11 treating all monitors as one big display. I bet if I oriented my monitors with two monitors in the center (one above and below) and the third to the right of the first two, I could at least get the dock on the left side of my center screen. Would love to see this be a bit more flexible. Thanks.

**Comment by kugelblitz** [comment]
@tstraus13 I think your request will be fulfilled as well if there is an option to keep the dock on the primary screen. You would probably want to make your center monitor primary (in XRandR's sense), and WindowMaker would detect where the primary monitor is (via XRRGetMonitors), and position the dock there.

So this probably does not need to be a big change, no universal flexibility, nothing like that. Just one checkbox.

**Comment by tstraus13** [comment]
Yes I think your are right if we could “pin” the dock to the primary monitor that would probably work. I would also say though that you should be able to drag the dock to any monitor but the ability to use the primary monitor would be the answer for most people. I noticed that when minimizing windows that they seem to be monitor aware in the sense that if on my right monitor it minimizes to that screen instead of the left monitor.

**Comment by d-torrance** [comment]
I've just submitted some patches that implement this to the mailing list.  See https://groups.google.com/g/wmaker-dev/c/LiB5sS3z8eo/m/rZUUTenhCQAJ.

**Comment by tstraus13** [comment]
Wow. Awesome. Thanks a lot! It’s a much appreciated feature.

**Comment by d-torrance** [comment]
This feature is now available on the `next` branch.  Let us know if there are any bugs!

**Comment by tstraus13** [comment]
Thanks again! Apologies for my lack of knowledge but is there any documentation for building/running the next branch? Or is it as simple as

`make`

and 

`make install`

Any dependencies?

**Comment by d-torrance** [comment]
http://www.windowmaker.org/docs/installation.html gives the basics, but it's assuming you're building from a tarball.  So start off with:

```
git clone https://repo.or.cz/wmaker-crm.git -b next
cd wmaker-crm
./autogen.sh
```

After that, it's the same.

**Comment by tstraus13** [comment]
I was just on the site. Must have missed that page somehow. Thanks.

**Comment by d-torrance** [comment]
I realized there's still a bit more to do.  While *moving* the dock will keep it on the primary screen now, it doesn't *start up* on the primary screen.  I'll work on it some more.

**Comment by kugelblitz** [comment]
Thank you! I will wait and then test on my system when you are finished.

**Comment by d-torrance** [comment]
I think I've addressed the missing things -- the latest patches are now on the `next` branch.

**Comment by d-torrance** [comment]
I'm discovering a few quirky bugs with this feature -- I'll list them here as I find them.

- [ ] When moving the dock from one side of the screen to the other, the icons for minimized applications move over a bit to make way for the dock.  But this happens on all heads, not just the primary one.
- [ ] When the dock is on the right of the primary head, right-clicking it pulls up a menu on the far right of the screen on a non-primary head.
- [ ] Restarting Window Maker sometimes move the dock from the right to the left.
