### ISSUE TITLE
libtiff update breaking wmaker

### ISSUE THREAD

**Issue by privacy313** [window-maker/wmaker#25]
hi there,

it seems the current libtiff version 4.5.0-1 breaks window maker.
on arch linux trying to startx returns the error `wmaker: error while loading shared libraries: libtiff.so.5: cannot open shared object file: No such file or directory`.
rolling back libtiff to the last version fixes the error but this breaks many other programs that are expecting the latest version.

how can i build wmaker with support for current libtiff?

**Comment by d-torrance** [comment]
You shouldn't need to do anything special beyond just building it again with the latest `libtiff`.  See http://www.windowmaker.org/docs/installation.html or http://www.windowmaker.org/docs/wmaker_install.html for instructions.

**Comment by privacy313** [comment]
working now. thanks for the help!
