### ISSUE TITLE
Can't unhide/unminimize

### ISSUE THREAD

**Issue by sthanduther** [window-maker/wmaker#29]
I'm having a trouble with the WMaker. Afet hiding windows (clicking in square) it's impossible to unhide.

I'm tried:
* Clicking two times;
* Clicking with left button and unhide.

I compiled with "--enable-debug --enable-usermenu".

**Comment by gryf** [comment]
I'm not sure if I understand the issue. If I right-click on the minimize button, all windows of the certain class will hide. They are still available on through window switcher (`alt-tab`) and under clip (icon will have one dot, like on the screenshot below:

![screenshot-2023-07-03_15-33-53](https://github.com/window-maker/wmaker/assets/264785/72902ea1-08c2-42c9-8b4d-b88db3711dc5)

after double clicking on that icon window(s) will unhide.

**Comment by sthanduther** [comment]
Well... 

> 
> I'm tried:
> 
>     Clicking two times;

**Comment by gryf** [comment]
Ok, so I guess, issue can be closed, as it works as intended.
