### ISSUE TITLE
WMRootMenu command cannot contain hyphen symbol

### ISSUE THREAD

**Issue by norayr** [window-maker/wmaker#30]
hello, i have this weird issue with menu.
i edit `~/GNUStep/Defaults/WMRootMenu` myself.

and when i add `netsurf`, the menu cannot be parsed

```
  (mrxvt, SHORTCUT, "Control+Mod+/", EXEC, mrxvt),
  ("Mozilla Firefox", EXEC, firefox),
  ("Netsurf", EXEC, /usr/bin/netsurf-gtk3),
  ("Lagrange", EXEC, "/usr/local/bin/lagrange.sh"),
  ("Mozilla Seamonkey", EXEC, seamonkey),
```

and it becomes the default menu.

however, if i create a file `/usr/local/bin/netsurf`

with this content

```
#!/bin/bash
/usr/bin/netsurf-gtk3
```

chmod it, and add to menu like this:

```
  ("Mozilla Firefox", EXEC, firefox),
  ("Netsurf", EXEC, /usr/local/bin/netsurf),
  ("Lagrange", EXEC, "/usr/local/bin/lagrange.sh"),

```

then menu shows netsurf.

so i tried this line:

`  ("xdemo", EXEC, /usr/bin/xscreensaver-demo),`

and again, menu doesn't show up.

so i guess hyphen in the command causes wmaker to not be able to parse the menu.

**Comment by gryf** [comment]
Its working for me. If you edit entries by hand, be careful about the quotations, i.e.:
```
…
("Mozilla Firefox", EXEC, firefox),
(Chromium, EXEC, "chromium --incognito"),
("FS-UAE", EXEC, "fs-uae"),
…
```

For single entries which doesn't contain space or hyphen, entry could be added without quotations, in other cases it should be enclosed with quotations.

**Comment by norayr** [comment]
true, it worked. but i was sure that it didn't, and that i tried.

thank you. let's close this issue.

**Comment by gryf** [comment]
Great to hear that!
