### ISSUE TITLE
command for WM restarting

### ISSUE THREAD

**Issue by sebqas** [window-maker/wmaker#37]
Is there any command (invoked in command line) to restart the  running WM ?

**Comment by gryf** [comment]
You can use signal `SIGUSR1` to do so (see NEWS file for details), i.e.
```
$ killall -SIGUSR1 wmaker
```
or, to be precise send that signal to the process which have `--for-real` parameter:
```
$ kill -SIGUSR1 $(ps aux | grep "[w]maker --for-real" |awk '{print $2}')
```

**Comment by sebqas** [comment]
thanks, the `--for-real` parameter is essential, otherwise, it kills wmaker with all child processes
